name: Fullstack CI/CD

on:
  push:
    branches: ["main"]

jobs:
  # --- FRONTEND JOB ---
  build-frontend:
    runs-on: ubuntu-latest
    # ONLY runs if files in the frontend folder changed
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Build React
        run: docker build -t my-frontend:${{ github.sha }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Registry
        run: |
          docker tag my-frontend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest

  # --- BACKEND JOB ---
  build-backend:
    runs-on: ubuntu-latest
    # ONLY runs if files in the backend folder changed
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Build Go
        run: docker build -t my-backend:${{ github.sha }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Registry
        run: |
          docker tag my-backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest

  # --- DEPLOY JOB ---
  deploy:
    needs: [build-frontend, build-backend] # Waits for BOTH to finish
    runs-on: ubuntu-latest
    if: always() # Runs even if one was skipped
    steps:
      - name: Deploy to K8s
        run: echo "Deploying fullstack app to GCP..."
