name: Fullstack CI/CD Pro

on:
  push:
    branches: ["main"]

jobs:
  # --- FRONTEND BUILD ---
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest

  # --- BACKEND BUILD ---
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest

  # --- DEPLOYMENT (The "ArgoCD" Simulation) ---
  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Deployment
        run: |
          echo "Images successfully pushed to Registry!"
          echo "Triggering ArgoCD sync for GKE Cluster..."
          echo "Frontend and Backend are now live."
